#!/bin/bash
#SBATCH --job-name=all_C_BOMEX_scalars_21600_48600
#SBATCH -p high-mem
#SBATCH -o ../jobs/out_%x.out
#SBATCH -e ../jobs/err_%x.err
#SBATCH --time=08:00:00
#SBATCH --mem=1000000
#SBATCH --nodes=2
 
# executable
source ~/myenv/bin/activate
python ../main_C_BOMEX_times.py
