#!/bin/bash
#SBATCH --job-name=C_BOMEX_14400
#SBATCH -p high-mem
#SBATCH -o /gws/nopw/j04/paracon_rdg/users/apower/LES_analysis/jobs/out_%x.out
#SBATCH -e /gws/nopw/j04/paracon_rdg/users/apower/LES_analysis/jobs/err_%x.err
#SBATCH --time=12:00:00
#SBATCH --mem=1000000
#SBATCH --nodes=2
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=a.power@pgr.reading.ac.uk
 
# executable
source ~/myenv/bin/activate
python /gws/nopw/j04/paracon_rdg/users/apower/LES_analysis/main_C_BOMEX.py
