#!/bin/bash
#SBATCH --job-name=dyn_BOMEX_14400_short
#SBATCH -p short-serial
#SBATCH -o /gws/nopw/j04/paracon_rdg/users/apower/LES_analysis/jobs/out_%x.out
#SBATCH -e /gws/nopw/j04/paracon_rdg/users/apower/LES_analysis/jobs/err_%x.err
#SBATCH --time=24:00:00
#SBATCH --mem=1000000
#SBATCH --nodes=1
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=a.power@pgr.reading.ac.uk
 
# executable
source ~/myenv/bin/activate
python /gws/nopw/j04/paracon_rdg/users/apower/LES_analysis/main_dynamic.py
