#!/bin/bash
#SBATCH --job-name=dyn_BOMEX_14400_4hr
#SBATCH -p short-serial-4hr
#SBATCH --account=short4hr
#SBATCH -o /gws/nopw/j04/paracon_rdg/users/apower/LES_analysis/jobs/out_%x.out
#SBATCH -e /gws/nopw/j04/paracon_rdg/users/apower/LES_analysis/jobs/err_%x.err
#SBATCH --time=4:00:00
#SBATCH --mem=64000
#SBATCH --nodes=1
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=a.power@pgr.reading.ac.uk
 
# executable
source ~/myenv/bin/activate
python /gws/nopw/j04/paracon_rdg/users/apower/LES_analysis/main_dynamic.py
